name: Split Firehol List

on:
  schedule:
    - cron: '0 0,12 * * *'  # Runs at 12 AM and 12 PM UTC
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  split_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "you@example.com"  # Replace with your email
          git config --global user.name "Your Name"          # Replace with your name

      - name: Download Firehol List
        run: |
          wget -O firehol_anonymous.netset "https://raw.githubusercontent.com/firehol/blocklist-ipsets/refs/heads/master/firehol_anonymous.netset"

      - name: Split the File
        run: |
          MAX_LINES=120000
          OUTPUT_PREFIX="firehol_anonymous_split_"
          split -l "$MAX_LINES" "firehol_anonymous.netset" "${OUTPUT_PREFIX}"

      - name: Add and Commit Changes
        run: |
          git add firehol_anonymous_split_*
          git commit -m "Update Firehol list files" || echo "No changes to commit"

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Use the provided GITHUB_TOKEN
        run: |
          git push origin main
