name: Split Firehol List

on:
  push:
    branches:
      - main  # Change to your default branch
    paths:
      - 'firehol_anonymous.netset'  # Trigger on changes to this file
  schedule:
    - cron: '0 12 * * *'  # Run every day at 12 PM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  split:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Firehol List
        run: |
          curl -s -o firehol_anonymous.netset https://raw.githubusercontent.com/firehol/blocklist-ipsets/refs/heads/master/firehol_anonymous.netset

      - name: Remove old files
        run: |
          rm -rf firewall_lists/*  # Remove all files in the firewall_lists directory

      - name: Split the file
        run: |
          mkdir -p firewall_lists
          split -l 120000 firehol_anonymous.netset firewall_lists/firehol_anonymous_

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add firewall_lists/*
          git commit -m "Update Firehol list files"
          git push https://x-access-token:${{ secrets.to1 }}@github.com/aref2232/split-iplist-for-fortigate.git
